version: '3.1'
services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nextjs-juejin-blog
    ports:
      - 3000:3000
    container_name: nextjs-juejin-blog-container